// rendering-perf-comparison/src/solid/TodoList.tsx
import { Component, For, Show } from "solid-js";
import { Todo } from "../types";
import TodoItem from "./TodoItem";

interface TodoListProps {
  todos: Todo[];
  onToggle: (id: number) => void;
  onDelete: (id: number) => void;
}

const TodoList: Component<TodoListProps> = (props) => {
  return (
    <div class="todo-list my-6">
      <h3 class="text-lg font-semibold mb-3">
        待办事项列表 ({props.todos.length})
      </h3>

      <Show
        when={props.todos.length > 0}
        fallback={<p class="text-gray-500">没有待办事项</p>}
      >
        <ul class="divide-y divide-gray-200 dark:divide-gray-700">
          <For each={props.todos}>
            {(todo) => (
              <TodoItem
                todo={todo}
                onToggle={props.onToggle}
                onDelete={props.onDelete}
              />
            )}
          </For>
        </ul>
      </Show>
    </div>
  );
};

export default TodoList;

// rendering-perf-comparison/src/react/TodoList.tsx
import React, { memo } from "react";
import { Todo } from "../types";
import TodoItem from "./TodoItem";

interface TodoListProps {
  todos: Todo[];
  onToggle: (id: number) => void;
  onDelete: (id: number) => void;
}

// 使用 memo 优化 TodoList 组件，只有当 todos 发生变化时才重新渲染
const TodoList: React.FC<TodoListProps> = memo(
  ({ todos, onToggle, onDelete }) => {
    return (
      <div className="todo-list my-6">
        <h3 className="text-lg font-semibold mb-3">
          待办事项列表 ({todos.length})
        </h3>

        {todos.length === 0 ? (
          <p className="text-gray-500">没有待办事项</p>
        ) : (
          <ul className="divide-y divide-gray-200 dark:divide-gray-700">
            {todos.map((todo) => (
              <TodoItem
                key={todo.id}
                todo={todo}
                onToggle={onToggle}
                onDelete={onDelete}
              />
            ))}
          </ul>
        )}
      </div>
    );
  }
);

export default TodoList;
